import type { Application, FieldDefinition, ReusableValue, StatusEvent } from "../types";

export const INITIAL_FIELDS: FieldDefinition[] = [
  { id: 1, key: "company", label: "Company", field_type: "text", required: true, visible: true, options: null, builtin: true, sort_order: 0 },
  { id: 2, key: "role", label: "Role", field_type: "text", required: true, visible: true, options: null, builtin: true, sort_order: 1 },
  { id: 3, key: "job_id", label: "Job ID", field_type: "text", required: false, visible: true, options: null, builtin: true, sort_order: 2 },
  { id: 4, key: "portal", label: "Portal", field_type: "select", required: false, visible: true, options: JSON.stringify(["LinkedIn", "Greenhouse", "Lever", "Workday", "Indeed", "jobrightai", "Other"]), builtin: true, sort_order: 3 },
  { id: 5, key: "location", label: "Location", field_type: "text", required: false, visible: true, options: null, builtin: true, sort_order: 4 },
  { id: 6, key: "salary_expectation", label: "Salary Expectation", field_type: "text", required: false, visible: true, options: null, builtin: true, sort_order: 5 },
  { id: 7, key: "work_model", label: "Work Model", field_type: "select", required: false, visible: true, options: JSON.stringify(["Remote", "Hybrid", "Onsite"]), builtin: false, sort_order: 6 },
  { id: 8, key: "tech_stack", label: "Tech Stack", field_type: "text", required: false, visible: true, options: null, builtin: false, sort_order: 7 },
  { id: 9, key: "referral_contact", label: "Referral Contact", field_type: "text", required: false, visible: true, options: null, builtin: false, sort_order: 8 },
];

export const INITIAL_REUSABLE_VALUES: ReusableValue[] = [
  { id: 1, category: "address", label: "Primary Residence", value: "742 Evergreen Terrace, San Francisco, CA 94107", is_default: true },
  { id: 2, category: "address", label: "Mailing Address", value: "P.O. Box 8821, San Francisco, CA 94107", is_default: false },
  { id: 3, category: "phone", label: "Mobile (Cell)", value: "+1 (415) 890-2341", is_default: true },
  { id: 4, category: "phone", label: "Work Direct", value: "+1 (415) 555-0198", is_default: false },
  { id: 5, category: "link", label: "Portfolio", value: "https://portfolio.dev", is_default: true },
  { id: 6, category: "link", label: "GitHub", value: "https://github.com/sahith", is_default: true },
  { id: 7, category: "link", label: "LinkedIn", value: "https://linkedin.com/in/sahith", is_default: true },
];

function daysAgo(days: number, hour = 14, min = 30): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(hour, min, 0, 0);
  return d.toISOString();
}

export const INITIAL_APPLICATIONS: Application[] = [
  {
    id: 1,
    company: "Stripe",
    role: "Staff Infrastructure Engineer",
    portal: "Greenhouse",
    job_url: "https://stripe.com/jobs/infrastructure-staff-9281",
    job_id: "STR-9281",
    location: "San Francisco, CA (Hybrid)",
    work_type: "Hybrid",
    address_used: "742 Evergreen Terrace, San Francisco, CA",
    phone: "+1 (415) 890-2341",
    salary_expectation: "$265,000",
    status: "offer",
    notes: "Offer package received! Verbal confirmation on $265k base + $180k equity/yr. Final decision deadline next Friday.",
    job_description: "Leading core global traffic infrastructure, Envoy proxy layers, and internal developer platform tooling.",
    resume_kind: "pdf",
    resume_tex: null,
    resume_path: "documents/stripe_staff_infra_resume.pdf",
    cover_kind: null,
    cover_tex: null,
    cover_path: null,
    captured_at: daysAgo(26, 10, 15),
    extra: {
      work_model: "Hybrid",
      tech_stack: "Go, Rust, Kubernetes, Envoy, AWS",
      referral_contact: "Alex Chen (Staff SWE)",
    },
    created_at: daysAgo(26, 10, 15),
  },
  {
    id: 2,
    company: "Linear",
    role: "Senior Full Stack Product Engineer",
    portal: "Ashby",
    job_url: "https://linear.app/careers/product-engineer",
    job_id: "LIN-104",
    location: "San Francisco, CA (Remote)",
    work_type: "Remote",
    address_used: "742 Evergreen Terrace, San Francisco, CA",
    phone: "+1 (415) 890-2341",
    salary_expectation: "$210,000",
    status: "interview",
    notes: "Completed take-home project with stellar feedback. System design & architecture deep dive with Karri scheduled for Wednesday at 2 PM.",
    job_description: "Building synchronization primitives, real-time client SQLite sync, and world-class product interactions.",
    resume_kind: "pdf",
    resume_tex: null,
    resume_path: "documents/linear_product_engineer_resume.pdf",
    cover_kind: "pdf",
    cover_tex: null,
    cover_path: "documents/linear_cover_letter.pdf",
    captured_at: daysAgo(18, 14, 20),
    extra: {
      work_model: "Remote",
      tech_stack: "TypeScript, React, Node.js, SQLite, WebSockets",
      referral_contact: "Tuomas Artman (CTO)",
    },
    created_at: daysAgo(18, 14, 20),
  },
  {
    id: 3,
    company: "Figma",
    role: "Senior Systems Engineer - Web Platform",
    portal: "Lever",
    job_url: "https://figma.com/careers/web-platform-eng",
    job_id: "FIG-882",
    location: "San Francisco, CA",
    work_type: "Hybrid",
    address_used: "742 Evergreen Terrace, San Francisco, CA",
    phone: "+1 (415) 890-2341",
    salary_expectation: "$235,000",
    status: "interview",
    notes: "Passed technical screen on WebAssembly rendering engine. Onsite round 2 next Tuesday (3 technical sessions + 1 leadership).",
    job_description: "Optimizing canvas rendering performance, memory layout, and C++/Rust WebAssembly modules.",
    resume_kind: "pdf",
    resume_tex: null,
    resume_path: "documents/figma_systems_resume.pdf",
    cover_kind: null,
    cover_tex: null,
    cover_path: null,
    captured_at: daysAgo(15, 11, 40),
    extra: {
      work_model: "Hybrid",
      tech_stack: "C++, Rust, WebAssembly, WebGL, TypeScript",
      referral_contact: "Sarah Jenkins",
    },
    created_at: daysAgo(15, 11, 40),
  },
  {
    id: 4,
    company: "Vercel",
    role: "Staff Developer Experience Engineer",
    portal: "Ashby",
    job_url: "https://vercel.com/careers/dx-engineer-staff",
    job_id: "VCL-450",
    location: "New York, NY (Remote)",
    work_type: "Remote",
    address_used: "742 Evergreen Terrace, San Francisco, CA",
    phone: "+1 (415) 890-2341",
    salary_expectation: "$220,000",
    status: "interview",
    notes: "Chatted with Lee Robinson regarding Next.js turbopack bundling integrations. Pair coding session next.",
    job_description: "Architecting developer workflows, compiler toolchains, and edge deployment automation.",
    resume_kind: "pdf",
    resume_tex: null,
    resume_path: "documents/vercel_dx_resume.pdf",
    cover_kind: null,
    cover_tex: null,
    cover_path: null,
    captured_at: daysAgo(12, 16, 10),
    extra: {
      work_model: "Remote",
      tech_stack: "Rust, Next.js, Turbo, TypeScript, Edge Runtime",
    },
    created_at: daysAgo(12, 16, 10),
  },
  {
    id: 5,
    company: "Notion",
    role: "Senior Backend Engineer - Data Infrastructure",
    portal: "Greenhouse",
    job_url: "https://notion.so/careers/backend-infra-sr",
    job_id: "NTN-731",
    location: "San Francisco, CA (Hybrid)",
    work_type: "Hybrid",
    address_used: "742 Evergreen Terrace, San Francisco, CA",
    phone: "+1 (415) 890-2341",
    salary_expectation: "$205,000",
    status: "screening",
    notes: "Recruiter screen with Jordan went great. Sent over availability for the technical coding interview.",
    job_description: "Scaling distributed database sharding, caching, and document block tree storage.",
    resume_kind: "pdf",
    resume_tex: null,
    resume_path: "documents/notion_backend_resume.pdf",
    cover_kind: null,
    cover_tex: null,
    cover_path: null,
    captured_at: daysAgo(8, 9, 30),
    extra: {
      work_model: "Hybrid",
      tech_stack: "PostgreSQL, Kotlin, Node.js, Redis, Kafka",
      referral_contact: "David Zhao",
    },
    created_at: daysAgo(8, 9, 30),
  },
  {
    id: 6,
    company: "Datadog",
    role: "Senior Distributed Systems Engineer",
    portal: "Greenhouse",
    job_url: "https://datadoghq.com/careers/distributed-systems-eng",
    job_id: "DD-9012",
    location: "Boston, MA (Hybrid)",
    work_type: "Hybrid",
    address_used: "742 Evergreen Terrace, San Francisco, CA",
    phone: "+1 (415) 890-2341",
    salary_expectation: "$195,000",
    status: "screening",
    notes: "Recruiter phone screen scheduled for Friday 11:30 AM EST.",
    job_description: "High-throughput metric ingestion pipelines processing millions of events per second.",
    resume_kind: "pdf",
    resume_tex: null,
    resume_path: "documents/datadog_resume.pdf",
    cover_kind: null,
    cover_tex: null,
    cover_path: null,
    captured_at: daysAgo(6, 15, 45),
    extra: {
      work_model: "Hybrid",
      tech_stack: "Go, Kafka, Cassandra, Kubernetes, Linux eBPF",
    },
    created_at: daysAgo(6, 15, 45),
  },
  {
    id: 7,
    company: "GitHub",
    role: "Principal Platform Architect",
    portal: "Greenhouse",
    job_url: "https://github.com/careers/platform-architect",
    job_id: "GH-339",
    location: "Remote (US)",
    work_type: "Remote",
    address_used: "742 Evergreen Terrace, San Francisco, CA",
    phone: "+1 (415) 890-2341",
    salary_expectation: "$270,000",
    status: "applied",
    notes: "Applied via employee referral link. Submitted custom cover letter highlighting developer workflows and CLI tooling experience.",
    job_description: "Guiding enterprise architecture for GitHub Actions, Codespaces, and repository hosting.",
    resume_kind: "pdf",
    resume_tex: null,
    resume_path: "documents/github_principal_resume.pdf",
    cover_kind: "pdf",
    cover_tex: null,
    cover_path: "documents/github_cover_letter.pdf",
    captured_at: daysAgo(5, 13, 0),
    extra: {
      work_model: "Remote",
      tech_stack: "Ruby, Go, Azure, Actions, Git Internals",
      referral_contact: "Marcus Vance",
    },
    created_at: daysAgo(5, 13, 0),
  },
  {
    id: 8,
    company: "Anthropic",
    role: "AI Tooling & Evaluation Infrastructure Engineer",
    portal: "Ashby",
    job_url: "https://anthropic.com/careers/tooling-evals-eng",
    job_id: "ANT-209",
    location: "San Francisco, CA (Hybrid)",
    work_type: "Hybrid",
    address_used: "742 Evergreen Terrace, San Francisco, CA",
    phone: "+1 (415) 890-2341",
    salary_expectation: "$290,000",
    status: "applied",
    notes: "Applied directly on Ashby portal. Application confirmation email received.",
    job_description: "Building agent evaluation harnesses, automated benchmarking frameworks, and inference telemetry.",
    resume_kind: "pdf",
    resume_tex: null,
    resume_path: "documents/anthropic_evals_resume.pdf",
    cover_kind: null,
    cover_tex: null,
    cover_path: null,
    captured_at: daysAgo(4, 17, 30),
    extra: {
      work_model: "Hybrid",
      tech_stack: "Python, Rust, PyTorch, Ray, PostgreSQL",
    },
    created_at: daysAgo(4, 17, 30),
  },
  {
    id: 9,
    company: "Airbnb",
    role: "Staff Frontend Architect",
    portal: "Greenhouse",
    job_url: "https://airbnb.com/careers/staff-frontend-architect",
    job_id: "ABNB-554",
    location: "San Francisco, CA (Remote)",
    work_type: "Remote",
    address_used: "742 Evergreen Terrace, San Francisco, CA",
    phone: "+1 (415) 890-2341",
    salary_expectation: "$240,000",
    status: "applied",
    notes: "Applied via LinkedIn Easy Apply with custom tailored portfolio attachment.",
    job_description: "Leading design system evolutions, server-driven UI, and micro-frontend federation.",
    resume_kind: "pdf",
    resume_tex: null,
    resume_path: "documents/airbnb_frontend_resume.pdf",
    cover_kind: null,
    cover_tex: null,
    cover_path: null,
    captured_at: daysAgo(3, 11, 15),
    extra: {
      work_model: "Remote",
      tech_stack: "React, TypeScript, GraphQL, Design Systems",
      referral_contact: "Elena Rostova",
    },
    created_at: daysAgo(3, 11, 15),
  },
  {
    id: 10,
    company: "OpenAI",
    role: "Core Infrastructure Engineer",
    portal: "Ashby",
    job_url: "https://openai.com/careers/core-infra",
    job_id: "OAI-118",
    location: "San Francisco, CA (Onsite)",
    work_type: "Onsite",
    address_used: "742 Evergreen Terrace, San Francisco, CA",
    phone: "+1 (415) 890-2341",
    salary_expectation: "$310,000",
    status: "applied",
    notes: "Captured automatically via JobTracker Chrome Extension. Application under review by recruiting team.",
    job_description: "Operating multi-cluster GPU training infrastructure, high-speed InfiniBand fabrics, and Slurm orchestration.",
    resume_kind: "pdf",
    resume_tex: null,
    resume_path: "documents/openai_core_infra_resume.pdf",
    cover_kind: null,
    cover_tex: null,
    cover_path: null,
    captured_at: daysAgo(2, 10, 0),
    extra: {
      work_model: "Onsite",
      tech_stack: "Kubernetes, Triton, Slurm, InfiniBand, Linux C/C++",
    },
    created_at: daysAgo(2, 10, 0),
  },
  {
    id: 11,
    company: "Cloudflare",
    role: "Senior Edge Compute Engineer",
    portal: "Greenhouse",
    job_url: "https://cloudflare.com/careers/edge-compute-sr",
    job_id: "CF-892",
    location: "Austin, TX (Hybrid)",
    work_type: "Hybrid",
    address_used: "742 Evergreen Terrace, San Francisco, CA",
    phone: "+1 (415) 890-2341",
    salary_expectation: "$190,000",
    status: "rejected",
    notes: "Role closed internally due to headcount redistribution. Recruiter requested to keep profile on file for Q4 openings.",
    job_description: "Workers runtime development, V8 isolate pooling, and low-latency DNS routing.",
    resume_kind: "pdf",
    resume_tex: null,
    resume_path: "documents/cloudflare_edge_resume.pdf",
    cover_kind: null,
    cover_tex: null,
    cover_path: null,
    captured_at: daysAgo(21, 14, 0),
    extra: {
      work_model: "Hybrid",
      tech_stack: "Rust, V8 Workers, Pingora, Linux Networking",
    },
    created_at: daysAgo(21, 14, 0),
  },
  {
    id: 12,
    company: "Supabase",
    role: "Database Platform Engineer",
    portal: "Ashby",
    job_url: "https://supabase.com/careers/postgres-infra-eng",
    job_id: "SUPA-77",
    location: "Remote (Global)",
    work_type: "Remote",
    address_used: "742 Evergreen Terrace, San Francisco, CA",
    phone: "+1 (415) 890-2341",
    salary_expectation: "$195,000",
    status: "interview",
    notes: "Postgres internals discussion with Paul Copplestone. Paired on WAL replication extension logic.",
    job_description: "Postgres core extension engineering, pgvector performance, and real-time CDC infrastructure.",
    resume_kind: "pdf",
    resume_tex: null,
    resume_path: "documents/supabase_resume.pdf",
    cover_kind: null,
    cover_tex: null,
    cover_path: null,
    captured_at: daysAgo(14, 16, 20),
    extra: {
      work_model: "Remote",
      tech_stack: "PostgreSQL, Elixir, Rust, Docker, Go",
    },
    created_at: daysAgo(14, 16, 20),
  },
  {
    id: 13,
    company: "Raycast",
    role: "macOS Core & Extensions Lead",
    portal: "Direct",
    job_url: "https://raycast.com/jobs/macos-core-lead",
    job_id: "RAY-042",
    location: "London, UK (Remote)",
    work_type: "Remote",
    address_used: "742 Evergreen Terrace, San Francisco, CA",
    phone: "+1 (415) 890-2341",
    salary_expectation: "$200,000",
    status: "screening",
    notes: "Initial async challenge completed in TypeScript/Swift. Conversation with Thomas Paul Mann scheduled.",
    job_description: "Extending native macOS launcher core, Node-to-Swift IPC bridges, and extension sandboxing.",
    resume_kind: "pdf",
    resume_tex: null,
    resume_path: "documents/raycast_resume.pdf",
    cover_kind: null,
    cover_tex: null,
    cover_path: null,
    captured_at: daysAgo(7, 12, 10),
    extra: {
      work_model: "Remote",
      tech_stack: "Swift, AppKit, React, Node.js, Rust",
      referral_contact: "Petr Nikolaev",
    },
    created_at: daysAgo(7, 12, 10),
  },
  {
    id: 14,
    company: "Tailscale",
    role: "Senior WireGuard Network Engineer",
    portal: "Lever",
    job_url: "https://tailscale.com/careers/network-eng",
    job_id: "TS-103",
    location: "Toronto, ON (Remote)",
    work_type: "Remote",
    address_used: "742 Evergreen Terrace, San Francisco, CA",
    phone: "+1 (415) 890-2341",
    salary_expectation: "$205,000",
    status: "applied",
    notes: "Applied with recommendation from Brad Fitzpatrick. Tailscale network packet filtering demo included.",
    job_description: "Mesh networking protocols, DERP relay servers, and cross-platform WireGuard clients.",
    resume_kind: "pdf",
    resume_tex: null,
    resume_path: "documents/tailscale_resume.pdf",
    cover_kind: null,
    cover_tex: null,
    cover_path: null,
    captured_at: daysAgo(1, 15, 0),
    extra: {
      work_model: "Remote",
      tech_stack: "Go, WireGuard, DERP, NAT Traversal, Linux Kernel",
      referral_contact: "Brad Fitzpatrick",
    },
    created_at: daysAgo(1, 15, 0),
  },
];

export const INITIAL_STATUS_EVENTS: Record<number, StatusEvent[]> = {
  1: [
    { status: "applied", changed_at: daysAgo(26) },
    { status: "screening", changed_at: daysAgo(20) },
    { status: "interview", changed_at: daysAgo(10) },
    { status: "offer", changed_at: daysAgo(1) },
  ],
  2: [
    { status: "applied", changed_at: daysAgo(18) },
    { status: "screening", changed_at: daysAgo(12) },
    { status: "interview", changed_at: daysAgo(2) },
  ],
  3: [
    { status: "applied", changed_at: daysAgo(15) },
    { status: "screening", changed_at: daysAgo(9) },
    { status: "interview", changed_at: daysAgo(3) },
  ],
};
